services:
  example:
    build: .
    tty: true
    network_mode: host
    environment:
      ROS_DOMAIN_ID: 10
      FASTRTPS_DEFAULT_PROFILES_FILE: /tmp/fastrtps-profile.xml
    volumes:
      - .:/root/ros2_ws
      - ./fastrtps-profile.xml:/tmp/fastrtps-profile.xml
